/* Copyright (c) 2021 Hasebe Masahiko. Released under the MIT license */

#ifndef msgf_h
#define msgf_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MAX_PART_NUM 1

#define MAX_BUFFER_SIZE 1024

#define SAMPLING_FREQ 44100.0

typedef struct Msgf Msgf;

struct Msgf *rust_msgf_new(void);

void rust_recieve_midi_message(struct Msgf *rust_msgf, uint8_t dt1, uint8_t dt2, uint8_t dt3);

void rust_process(struct Msgf *rust_msgf,
                  float (*abuf)[MAX_BUFFER_SIZE],
                  uint32_t in_number_frames);

void rust_reduce_resource(struct Msgf *rust_msgf);

void say_hello(void);

void rust_msgf_destroy(struct Msgf *rust_msgf);

#endif /* msgf_h */
